version: '3.3'

services:
  wp-db:
    image: mysql:5.7
    restart: on-failure
    volumes:
      - wp-db:/var/lib/mysql
    command: --explicit_defaults_for_timestamp
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  wordpress:
    depends_on:
      - wp-db
    image: wordpress:latest
    restart: on-failure
    volumes:
      - ./wp-theme:/var/www/html/wp-content/themes/ultrasimpleRes
    ports:
      - '8051:80'
    environment:
      WORDPRESS_DB_HOST: wp-db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress

volumes:
  wp-db:
