version: '3.3'

services:
  db:
    image: postgres:9.6
    volumes:
      - pin-db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data

  react:
    build: ./react/
    command: sh -c 'yarn install && yarn start'
    env_file:
      - .env
    volumes:
      - ./react/:/code
    ports:
      - '3050:3050'
    depends_on:
      - server

  server:
    image: devtc/pin-dashboard-server:develop
    build: ./server/
    command: bash -c '/code/scripts/wait-for-it.sh db:5432 && /code/scripts/run_develop.sh'
    env_file:
      - .env
    volumes:
      - ./server/:/code
    ports:
      - '8050:8050'
    depends_on:
      - db
      - redis

volumes:
  pin-db:
  redis-data:
