# Generated by Django 2.2.3 on 2019-07-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('last_updated_at', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
