# Generated by Django 2.2.3 on 2019-07-10 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
                ('place', models.CharField(blank=True, max_length=256)),
                ('ward', models.CharField(blank=True, max_length=256, null=True)),
                ('category', models.CharField(blank=True, max_length=256)),
                ('risk_score', models.CharField(blank=True, max_length=256)),
                ('high_risk_of', models.CharField(blank=True, max_length=256)),
                ('direct_risk_for', models.CharField(blank=True, max_length=256)),
                ('potential_impact', models.CharField(blank=True, max_length=256)),
                ('risk_probability', models.CharField(blank=True, max_length=256)),
                ('mitigation_work_by', models.CharField(blank=True, max_length=256)),
                ('status', models.CharField(blank=True, max_length=256)),
                ('district', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.District')),
                ('palika', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.Palika')),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('place', models.CharField(blank=True, max_length=256)),
                ('ward', models.CharField(blank=True, max_length=256, null=True)),
                ('land_size', models.FloatField(blank=True, default=None, null=True)),
                ('eligibility_source', models.CharField(blank=True, max_length=256)),
                ('eligibility', models.CharField(blank=True, max_length=256)),
                ('application', models.CharField(blank=True, max_length=256)),
                ('result', models.CharField(blank=True, max_length=256)),
                ('total_male', models.IntegerField(blank=True, default=None, null=True)),
                ('total_female', models.IntegerField(blank=True, default=None, null=True)),
                ('men_0_5', models.IntegerField(blank=True, default=None, null=True)),
                ('men_6_18', models.IntegerField(blank=True, default=None, null=True)),
                ('men_19_60', models.IntegerField(blank=True, default=None, null=True)),
                ('men_60_plus', models.IntegerField(blank=True, default=None, null=True)),
                ('women_0_5', models.IntegerField(blank=True, default=None, null=True)),
                ('women_6_18', models.IntegerField(blank=True, default=None, null=True)),
                ('women_19_60', models.IntegerField(blank=True, default=None, null=True)),
                ('women_60_plus', models.IntegerField(blank=True, default=None, null=True)),
                ('other', models.IntegerField(blank=True, default=None, null=True)),
                ('district', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.District')),
                ('geosite', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.GeoSite')),
                ('palika', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.Palika')),
            ],
        ),
    ]
