# Generated by Django 2.2.3 on 2019-07-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_auto_20190712_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='relocated_lat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='relocated_lng',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='solution_type',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
