# Generated by Django 2.2.3 on 2019-07-25 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_ward'),
        ('metadata', '0003_auto_20190716_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelocationSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
                ('place', models.CharField(blank=True, max_length=256)),
                ('protection_support', models.CharField(blank=True, max_length=256)),
                ('technical_support', models.CharField(blank=True, max_length=256)),
                ('site_type', models.CharField(blank=True, max_length=256)),
                ('district', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.District')),
                ('palika', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.Palika')),
                ('ward', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.Ward')),
            ],
        ),
        migrations.AddField(
            model_name='household',
            name='relocation_site',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.RelocationSite'),
        ),
    ]
