# Generated by Django 2.2.3 on 2019-07-25 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_auto_20190725_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relocationsite',
            name='technical_support',
        ),
    ]
