# Generated by Django 2.2.3 on 2019-08-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_remove_relocationsite_technical_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='relocated_lat',
        ),
        migrations.RemoveField(
            model_name='household',
            name='relocated_lng',
        ),
        migrations.RemoveField(
            model_name='household',
            name='solution_type',
        ),
        migrations.AddField(
            model_name='household',
            name='tranches',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
