# Generated by Django 2.2.3 on 2019-08-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0006_auto_20190803_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='relocationsite',
            name='status',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
