# Generated by Django 2.2.3 on 2019-09-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0009_auto_20190804_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='relocationsite',
            name='technical_support',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
