# Generated by Django 2.2.3 on 2019-07-12 05:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20190711_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('palika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Palika')),
            ],
        ),
    ]
