# Generated by Django 2.2.5 on 2019-09-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='palika',
            name='type',
            field=models.CharField(blank=True, choices=[('nagarpalika', 'Nagarpalika'), ('gaunpalika', 'Gaunpalika'), ('metro', 'Metropolitan City'), ('sub_metro', 'Sub-Metropolitan City')], max_length=50, null=True),
        ),
    ]
